#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MapsSample.Resource", IsApplication=true)]

namespace MapsSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int layers_array = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int common_signin_btn_text_dark = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_signin_btn_text_light = 2131034123;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int badge_nsw = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int badge_qld = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int badge_sa = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int badge_victoria = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int badge_wa = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_full_open_on_phone = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_ic_googleplayservices = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_disabled_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_disabled_focus_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_disabled_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_focus_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_focus_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_normal_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_icon_normal_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_icon_pressed_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_icon_pressed_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_disabled_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_disabled_focus_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_disabled_focus_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_disabled_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_focus_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_focus_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_normal_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_text_normal_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_text_pressed_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_text_pressed_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int custom_info_bubble = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_launcher = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int monoandroidsplash = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int newark_nj_1922 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int newark_prudential_sunny = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int pegman = 2130837541;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0005
			public const int adjust_height = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int adjust_width = 2131361798;
			
			// aapt resource value: 0x7f0a0017
			public const int alphaSeekBar = 2131361815;
			
			// aapt resource value: 0x7f0a0009
			public const int animate = 2131361801;
			
			// aapt resource value: 0x7f0a0019
			public const int badge = 2131361817;
			
			// aapt resource value: 0x7f0a0015
			public const int bondi = 2131361813;
			
			// aapt resource value: 0x7f0a0029
			public const int buildings = 2131361833;
			
			// aapt resource value: 0x7f0a001d
			public const int camera_text = 2131361821;
			
			// aapt resource value: 0x7f0a0048
			public const int change_camera = 2131361864;
			
			// aapt resource value: 0x7f0a0047
			public const int change_pano = 2131361863;
			
			// aapt resource value: 0x7f0a0049
			public const int click_pano = 2131361865;
			
			// aapt resource value: 0x7f0a005a
			public const int compass_toggle = 2131361882;
			
			// aapt resource value: 0x7f0a0038
			public const int custom_info_contents = 2131361848;
			
			// aapt resource value: 0x7f0a0039
			public const int custom_info_window = 2131361849;
			
			// aapt resource value: 0x7f0a0036
			public const int custom_info_window_options = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int default_info_window = 2131361847;
			
			// aapt resource value: 0x7f0a001e
			public const int description = 2131361822;
			
			// aapt resource value: 0x7f0a0013
			public const int duration_bar = 2131361811;
			
			// aapt resource value: 0x7f0a0012
			public const int duration_toggle = 2131361810;
			
			// aapt resource value: 0x7f0a0058
			public const int fade_in_toggle = 2131361880;
			
			// aapt resource value: 0x7f0a0034
			public const int flat = 2131361844;
			
			// aapt resource value: 0x7f0a0022
			public const int focused_bulding_info_button = 2131361826;
			
			// aapt resource value: 0x7f0a0024
			public const int focused_level_info_button = 2131361828;
			
			// aapt resource value: 0x7f0a0042
			public const int get_my_location_button = 2131361858;
			
			// aapt resource value: 0x7f0a004b
			public const int get_position = 2131361867;
			
			// aapt resource value: 0x7f0a002e
			public const int go_to_adelaide = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int go_to_australia = 2131361839;
			
			// aapt resource value: 0x7f0a002d
			public const int go_to_darwin = 2131361837;
			
			// aapt resource value: 0x7f0a0025
			public const int higher_level_button = 2131361829;
			
			// aapt resource value: 0x7f0a0016
			public const int hueSeekBar = 2131361814;
			
			// aapt resource value: 0x7f0a0000
			public const int hybrid = 2131361792;
			
			// aapt resource value: 0x7f0a002a
			public const int indoor = 2131361834;
			
			// aapt resource value: 0x7f0a0043
			public const int instructions = 2131361859;
			
			// aapt resource value: 0x7f0a0053
			public const int invalid = 2131361875;
			
			// aapt resource value: 0x7f0a0026
			public const int layers_spinner = 2131361830;
			
			// aapt resource value: 0x7f0a002b
			public const int legal_info = 2131361835;
			
			// aapt resource value: 0x7f0a0030
			public const int list = 2131361840;
			
			// aapt resource value: 0x7f0a002c
			public const int lite_demo_introtext = 2131361836;
			
			// aapt resource value: 0x7f0a0032
			public const int lite_listrow_map = 2131361842;
			
			// aapt resource value: 0x7f0a0031
			public const int lite_listrow_text = 2131361841;
			
			// aapt resource value: 0x7f0a004a
			public const int long_click_pano = 2131361866;
			
			// aapt resource value: 0x7f0a0007
			public const int map = 2131361799;
			
			// aapt resource value: 0x7f0a003c
			public const int map1 = 2131361852;
			
			// aapt resource value: 0x7f0a003d
			public const int map2 = 2131361853;
			
			// aapt resource value: 0x7f0a003f
			public const int map3 = 2131361855;
			
			// aapt resource value: 0x7f0a0040
			public const int map4 = 2131361856;
			
			// aapt resource value: 0x7f0a003a
			public const int map_container = 2131361850;
			
			// aapt resource value: 0x7f0a003b
			public const int map_container1 = 2131361851;
			
			// aapt resource value: 0x7f0a003e
			public const int map_container2 = 2131361854;
			
			// aapt resource value: 0x7f0a0066
			public const int menu_legal = 2131361894;
			
			// aapt resource value: 0x7f0a0041
			public const int message_text = 2131361857;
			
			// aapt resource value: 0x7f0a004c
			public const int move_position = 2131361868;
			
			// aapt resource value: 0x7f0a0028
			public const int my_location = 2131361832;
			
			// aapt resource value: 0x7f0a005b
			public const int mylocationbutton_toggle = 2131361883;
			
			// aapt resource value: 0x7f0a005c
			public const int mylocationlayer_toggle = 2131361884;
			
			// aapt resource value: 0x7f0a0055
			public const int navigation = 2131361877;
			
			// aapt resource value: 0x7f0a0001
			public const int none = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int normal = 2131361794;
			
			// aapt resource value: 0x7f0a0033
			public const int pager = 2131361843;
			
			// aapt resource value: 0x7f0a004f
			public const int pan_down = 2131361871;
			
			// aapt resource value: 0x7f0a004d
			public const int pan_left = 2131361869;
			
			// aapt resource value: 0x7f0a0050
			public const int pan_right = 2131361872;
			
			// aapt resource value: 0x7f0a004e
			public const int pan_up = 2131361870;
			
			// aapt resource value: 0x7f0a0057
			public const int panning = 2131361879;
			
			// aapt resource value: 0x7f0a0060
			public const int rotate_toggle = 2131361888;
			
			// aapt resource value: 0x7f0a0035
			public const int rotationSeekBar = 2131361845;
			
			// aapt resource value: 0x7f0a0051
			public const int sanfran = 2131361873;
			
			// aapt resource value: 0x7f0a0052
			public const int santorini = 2131361874;
			
			// aapt resource value: 0x7f0a0003
			public const int satellite = 2131361795;
			
			// aapt resource value: 0x7f0a000c
			public const int scroll_down = 2131361804;
			
			// aapt resource value: 0x7f0a000a
			public const int scroll_left = 2131361802;
			
			// aapt resource value: 0x7f0a000d
			public const int scroll_right = 2131361805;
			
			// aapt resource value: 0x7f0a005d
			public const int scroll_toggle = 2131361885;
			
			// aapt resource value: 0x7f0a000b
			public const int scroll_up = 2131361803;
			
			// aapt resource value: 0x7f0a0044
			public const int snapshot_holder = 2131361860;
			
			// aapt resource value: 0x7f0a001b
			public const int snippet = 2131361819;
			
			// aapt resource value: 0x7f0a0008
			public const int stop_animation = 2131361800;
			
			// aapt resource value: 0x7f0a0054
			public const int streetnames = 2131361876;
			
			// aapt resource value: 0x7f0a0046
			public const int streetviewpanorama = 2131361862;
			
			// aapt resource value: 0x7f0a0020
			public const int switchImage = 2131361824;
			
			// aapt resource value: 0x7f0a0014
			public const int sydney = 2131361812;
			
			// aapt resource value: 0x7f0a001c
			public const int tap_text = 2131361820;
			
			// aapt resource value: 0x7f0a0004
			public const int terrain = 2131361796;
			
			// aapt resource value: 0x7f0a0011
			public const int tilt_less = 2131361809;
			
			// aapt resource value: 0x7f0a0010
			public const int tilt_more = 2131361808;
			
			// aapt resource value: 0x7f0a005f
			public const int tilt_toggle = 2131361887;
			
			// aapt resource value: 0x7f0a001a
			public const int title = 2131361818;
			
			// aapt resource value: 0x7f0a0023
			public const int toggle_level_picker_button = 2131361827;
			
			// aapt resource value: 0x7f0a0021
			public const int top_text = 2131361825;
			
			// aapt resource value: 0x7f0a0027
			public const int traffic = 2131361831;
			
			// aapt resource value: 0x7f0a001f
			public const int transparencySeekBar = 2131361823;
			
			// aapt resource value: 0x7f0a0065
			public const int vr_aus_button = 2131361893;
			
			// aapt resource value: 0x7f0a0062
			public const int vr_more_padded_button = 2131361890;
			
			// aapt resource value: 0x7f0a0061
			public const int vr_normal_button = 2131361889;
			
			// aapt resource value: 0x7f0a0064
			public const int vr_sfo_button = 2131361892;
			
			// aapt resource value: 0x7f0a0063
			public const int vr_soh_button = 2131361891;
			
			// aapt resource value: 0x7f0a0045
			public const int wait_for_map_load = 2131361861;
			
			// aapt resource value: 0x7f0a0018
			public const int widthSeekBar = 2131361816;
			
			// aapt resource value: 0x7f0a0056
			public const int zoom = 2131361878;
			
			// aapt resource value: 0x7f0a0059
			public const int zoom_buttons_toggle = 2131361881;
			
			// aapt resource value: 0x7f0a005e
			public const int zoom_gestures_toggle = 2131361886;
			
			// aapt resource value: 0x7f0a000e
			public const int zoom_in = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int zoom_out = 2131361807;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int basic_demo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int camera_demo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int circle_demo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int custom_info_contents = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int custom_info_window = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int events_demo = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int feature = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ground_overlay_demo = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int indoor_demo = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int layers_demo = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int legal_info = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int lite_demo = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int lite_list_demo = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int lite_list_demo_row = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int main = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int map_in_pager_demo = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int marker_demo = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int multimap_demo = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int my_location_demo = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int options_demo = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int polygon_demo = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int polyline_demo = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int raw_mapview_demo = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int save_state_demo = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int snapshot_demo = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int split_street_view_panorama_and_map_demo = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int street_view_panorama_basic_demo = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int street_view_panorama_events_demo = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int street_view_panorama_navigation_demo = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int street_view_panorama_options_demo = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int street_view_panorama_view_demo = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int text_fragment = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int tile_coordinate_demo = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int tile_overlay_demo = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int ui_settings_demo = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int visible_region_demo = 2130903075;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int activity_main = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04009d
			public const int activate_higher_level = 2130968733;
			
			// aapt resource value: 0x7f040022
			public const int alpha = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int animate = 2130968611;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040025
			public const int basic_map_demo_description = 2130968613;
			
			// aapt resource value: 0x7f040024
			public const int basic_map_demo_label = 2130968612;
			
			// aapt resource value: 0x7f040026
			public const int buildings = 2130968614;
			
			// aapt resource value: 0x7f040028
			public const int camera_demo_description = 2130968616;
			
			// aapt resource value: 0x7f040027
			public const int camera_demo_label = 2130968615;
			
			// aapt resource value: 0x7f04002a
			public const int circle_demo_description = 2130968618;
			
			// aapt resource value: 0x7f040029
			public const int circle_demo_label = 2130968617;
			
			// aapt resource value: 0x7f04002b
			public const int clear_map = 2130968619;
			
			// aapt resource value: 0x7f040004
			public const int common_android_wear_notification_needs_update_text = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int common_android_wear_update_text = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int common_android_wear_update_title = 2130968591;
			
			// aapt resource value: 0x7f04001d
			public const int common_google_play_services_api_unavailable_text = 2130968605;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_enable_button = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_enable_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_enable_title = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_error_notification_requested_by_msg = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_install_button = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_install_text_phone = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_install_text_tablet = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_title = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int common_google_play_services_invalid_account_text = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_invalid_account_title = 2130968598;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_needs_enabling_title = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_network_error_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_network_error_title = 2130968596;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_needs_update_title = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_notification_ticker = 2130968578;
			
			// aapt resource value: 0x7f04001f
			public const int common_google_play_services_sign_in_failed_text = 2130968607;
			
			// aapt resource value: 0x7f04001e
			public const int common_google_play_services_sign_in_failed_title = 2130968606;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_unknown_issue = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_unsupported_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_unsupported_title = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_update_button = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_update_text = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_update_title = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_updating_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_updating_title = 2130968594;
			
			// aapt resource value: 0x7f04001c
			public const int common_open_on_phone = 2130968604;
			
			// aapt resource value: 0x7f040020
			public const int common_signin_button_text = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int common_signin_button_text_long = 2130968609;
			
			// aapt resource value: 0x7f04002c
			public const int compass = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int custom_info_contents = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int custom_info_window = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int default_info_window = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int demo_title = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int down_arrow = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int drag_melbourne = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int duration = 2130968627;
			
			// aapt resource value: 0x7f040036
			public const int events_demo_description = 2130968630;
			
			// aapt resource value: 0x7f040035
			public const int events_demo_label = 2130968629;
			
			// aapt resource value: 0x7f040037
			public const int fade_in = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int fill_alpha = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int fill_hue = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int flat = 2130968634;
			
			// aapt resource value: 0x7f04009e
			public const int focused_building_info = 2130968734;
			
			// aapt resource value: 0x7f04009f
			public const int focused_level_info = 2130968735;
			
			// aapt resource value: 0x7f04003b
			public const int go_to_bondi = 2130968635;
			
			// aapt resource value: 0x7f0400a3
			public const int go_to_invalid = 2130968739;
			
			// aapt resource value: 0x7f0400a4
			public const int go_to_san_fran = 2130968740;
			
			// aapt resource value: 0x7f04003c
			public const int go_to_santorini = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int go_to_sydney = 2130968637;
			
			// aapt resource value: 0x7f04003f
			public const int ground_overlay_demo_description = 2130968639;
			
			// aapt resource value: 0x7f04003e
			public const int ground_overlay_demo_label = 2130968638;
			
			// aapt resource value: 0x7f040034
			public const int hue = 2130968628;
			
			// aapt resource value: 0x7f040040
			public const int hybrid = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int indoor = 2130968641;
			
			// aapt resource value: 0x7f0400a0
			public const int indoor_demo_description = 2130968736;
			
			// aapt resource value: 0x7f0400a1
			public const int indoor_demo_label = 2130968737;
			
			// aapt resource value: 0x7f040043
			public const int layers_demo_description = 2130968643;
			
			// aapt resource value: 0x7f040042
			public const int layers_demo_label = 2130968642;
			
			// aapt resource value: 0x7f040044
			public const int left_arrow = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int legal_info = 2130968645;
			
			// aapt resource value: 0x7f040096
			public const int lite_demo_description = 2130968726;
			
			// aapt resource value: 0x7f040097
			public const int lite_demo_intro = 2130968727;
			
			// aapt resource value: 0x7f040095
			public const int lite_demo_label = 2130968725;
			
			// aapt resource value: 0x7f040099
			public const int lite_go_to_adelaide = 2130968729;
			
			// aapt resource value: 0x7f04009a
			public const int lite_go_to_australia = 2130968730;
			
			// aapt resource value: 0x7f040098
			public const int lite_go_to_darwin = 2130968728;
			
			// aapt resource value: 0x7f04009c
			public const int lite_list_demo_description = 2130968732;
			
			// aapt resource value: 0x7f04009b
			public const int lite_list_demo_label = 2130968731;
			
			// aapt resource value: 0x7f040047
			public const int location_source_demo_description = 2130968647;
			
			// aapt resource value: 0x7f040046
			public const int location_source_demo_label = 2130968646;
			
			// aapt resource value: 0x7f0400b9
			public const int long_press_screen = 2130968761;
			
			// aapt resource value: 0x7f04004a
			public const int map_in_pager_demo_description = 2130968650;
			
			// aapt resource value: 0x7f040049
			public const int map_in_pager_demo_label = 2130968649;
			
			// aapt resource value: 0x7f040048
			public const int map_not_ready = 2130968648;
			
			// aapt resource value: 0x7f04004c
			public const int marker_demo_description = 2130968652;
			
			// aapt resource value: 0x7f04004b
			public const int marker_demo_label = 2130968651;
			
			// aapt resource value: 0x7f04004d
			public const int move_the_camera = 2130968653;
			
			// aapt resource value: 0x7f04004f
			public const int multi_map_demo_description = 2130968655;
			
			// aapt resource value: 0x7f04004e
			public const int multi_map_demo_label = 2130968654;
			
			// aapt resource value: 0x7f040050
			public const int my_location = 2130968656;
			
			// aapt resource value: 0x7f040052
			public const int my_location_demo_description = 2130968658;
			
			// aapt resource value: 0x7f040051
			public const int my_location_demo_label = 2130968657;
			
			// aapt resource value: 0x7f040053
			public const int mylocation_button = 2130968659;
			
			// aapt resource value: 0x7f040054
			public const int mylocation_layer = 2130968660;
			
			// aapt resource value: 0x7f0400a5
			public const int navigate_to_another_panorama = 2130968741;
			
			// aapt resource value: 0x7f0400a6
			public const int navigation = 2130968742;
			
			// aapt resource value: 0x7f040055
			public const int no_demos = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int none_map = 2130968662;
			
			// aapt resource value: 0x7f040057
			public const int normal = 2130968663;
			
			// aapt resource value: 0x7f040059
			public const int options_demo_description = 2130968665;
			
			// aapt resource value: 0x7f040058
			public const int options_demo_label = 2130968664;
			
			// aapt resource value: 0x7f0400a7
			public const int pan_camera = 2130968743;
			
			// aapt resource value: 0x7f0400a8
			public const int panning = 2130968744;
			
			// aapt resource value: 0x7f0400a9
			public const int panorama_not_ready = 2130968745;
			
			// aapt resource value: 0x7f04005a
			public const int play_services_not_installed = 2130968666;
			
			// aapt resource value: 0x7f04005c
			public const int polygon_demo_description = 2130968668;
			
			// aapt resource value: 0x7f04005b
			public const int polygon_demo_label = 2130968667;
			
			// aapt resource value: 0x7f04005e
			public const int polyline_demo_description = 2130968670;
			
			// aapt resource value: 0x7f04005d
			public const int polyline_demo_label = 2130968669;
			
			// aapt resource value: 0x7f040060
			public const int programmatic_demo_description = 2130968672;
			
			// aapt resource value: 0x7f04005f
			public const int programmatic_demo_label = 2130968671;
			
			// aapt resource value: 0x7f040061
			public const int properties_circle = 2130968673;
			
			// aapt resource value: 0x7f040063
			public const int properties_sydney_polygon = 2130968675;
			
			// aapt resource value: 0x7f040062
			public const int properties_sydney_polyline = 2130968674;
			
			// aapt resource value: 0x7f040066
			public const int raw_map_view_demo_description = 2130968678;
			
			// aapt resource value: 0x7f040065
			public const int raw_map_view_demo_label = 2130968677;
			
			// aapt resource value: 0x7f0400aa
			public const int request_position = 2130968746;
			
			// aapt resource value: 0x7f040067
			public const int reset_map = 2130968679;
			
			// aapt resource value: 0x7f040069
			public const int retain_map_demo_description = 2130968681;
			
			// aapt resource value: 0x7f040068
			public const int retain_map_demo_label = 2130968680;
			
			// aapt resource value: 0x7f04006a
			public const int right_arrow = 2130968682;
			
			// aapt resource value: 0x7f040064
			public const int rotate = 2130968676;
			
			// aapt resource value: 0x7f04006b
			public const int rotation = 2130968683;
			
			// aapt resource value: 0x7f04006c
			public const int satellite = 2130968684;
			
			// aapt resource value: 0x7f04006e
			public const int save_state_demo_description = 2130968686;
			
			// aapt resource value: 0x7f04006d
			public const int save_state_demo_label = 2130968685;
			
			// aapt resource value: 0x7f04006f
			public const int save_state_instructions = 2130968687;
			
			// aapt resource value: 0x7f040070
			public const int scroll = 2130968688;
			
			// aapt resource value: 0x7f040071
			public const int snapshot_clear_button = 2130968689;
			
			// aapt resource value: 0x7f040073
			public const int snapshot_demo_description = 2130968691;
			
			// aapt resource value: 0x7f040072
			public const int snapshot_demo_label = 2130968690;
			
			// aapt resource value: 0x7f040074
			public const int snapshot_holder_description = 2130968692;
			
			// aapt resource value: 0x7f040075
			public const int snapshot_take_button = 2130968693;
			
			// aapt resource value: 0x7f0400ab
			public const int split_street_view_panorama_and_map_demo_description = 2130968747;
			
			// aapt resource value: 0x7f0400ac
			public const int split_street_view_panorama_and_map_demo_label = 2130968748;
			
			// aapt resource value: 0x7f040076
			public const int stop_animation = 2130968694;
			
			// aapt resource value: 0x7f0400ad
			public const int street_view_panorama_basic_demo_description = 2130968749;
			
			// aapt resource value: 0x7f0400ae
			public const int street_view_panorama_basic_demo_label = 2130968750;
			
			// aapt resource value: 0x7f0400af
			public const int street_view_panorama_events_demo_description = 2130968751;
			
			// aapt resource value: 0x7f0400b0
			public const int street_view_panorama_events_demo_label = 2130968752;
			
			// aapt resource value: 0x7f0400b1
			public const int street_view_panorama_navigation_demo_description = 2130968753;
			
			// aapt resource value: 0x7f0400b2
			public const int street_view_panorama_navigation_demo_label = 2130968754;
			
			// aapt resource value: 0x7f0400b3
			public const int street_view_panorama_options_demo_description = 2130968755;
			
			// aapt resource value: 0x7f0400b4
			public const int street_view_panorama_options_demo_label = 2130968756;
			
			// aapt resource value: 0x7f0400b5
			public const int street_view_panorama_view_demo_description = 2130968757;
			
			// aapt resource value: 0x7f0400b6
			public const int street_view_panorama_view_demo_label = 2130968758;
			
			// aapt resource value: 0x7f0400b7
			public const int streetnames = 2130968759;
			
			// aapt resource value: 0x7f040077
			public const int stroke_width = 2130968695;
			
			// aapt resource value: 0x7f040078
			public const int swipe = 2130968696;
			
			// aapt resource value: 0x7f040079
			public const int switch_image = 2130968697;
			
			// aapt resource value: 0x7f04007a
			public const int tap_instructions = 2130968698;
			
			// aapt resource value: 0x7f0400b8
			public const int tap_screen = 2130968760;
			
			// aapt resource value: 0x7f04007b
			public const int terrain = 2130968699;
			
			// aapt resource value: 0x7f04007d
			public const int tile_coordinate_demo_description = 2130968701;
			
			// aapt resource value: 0x7f04007c
			public const int tile_coordinate_demo_label = 2130968700;
			
			// aapt resource value: 0x7f04007f
			public const int tile_overlay_demo_description = 2130968703;
			
			// aapt resource value: 0x7f04007e
			public const int tile_overlay_demo_label = 2130968702;
			
			// aapt resource value: 0x7f040080
			public const int tilt = 2130968704;
			
			// aapt resource value: 0x7f040081
			public const int tilt_less = 2130968705;
			
			// aapt resource value: 0x7f040082
			public const int tilt_more = 2130968706;
			
			// aapt resource value: 0x7f0400a2
			public const int toggle_level_picker = 2130968738;
			
			// aapt resource value: 0x7f040083
			public const int traffic = 2130968707;
			
			// aapt resource value: 0x7f040084
			public const int transparency = 2130968708;
			
			// aapt resource value: 0x7f040086
			public const int ui_settings_demo_description = 2130968710;
			
			// aapt resource value: 0x7f040085
			public const int ui_settings_demo_label = 2130968709;
			
			// aapt resource value: 0x7f040087
			public const int up_arrow = 2130968711;
			
			// aapt resource value: 0x7f040089
			public const int visible_region_demo_description = 2130968713;
			
			// aapt resource value: 0x7f040088
			public const int visible_region_demo_label = 2130968712;
			
			// aapt resource value: 0x7f04008a
			public const int vr_aus_button = 2130968714;
			
			// aapt resource value: 0x7f04008c
			public const int vr_more_padded_button = 2130968716;
			
			// aapt resource value: 0x7f04008b
			public const int vr_normal_button = 2130968715;
			
			// aapt resource value: 0x7f04008e
			public const int vr_sfo_button = 2130968718;
			
			// aapt resource value: 0x7f04008d
			public const int vr_soh_button = 2130968717;
			
			// aapt resource value: 0x7f04008f
			public const int wait_for_map_load = 2130968719;
			
			// aapt resource value: 0x7f0400ba
			public const int walk_panorama = 2130968762;
			
			// aapt resource value: 0x7f040090
			public const int width = 2130968720;
			
			// aapt resource value: 0x7f040091
			public const int zoom_buttons = 2130968721;
			
			// aapt resource value: 0x7f040092
			public const int zoom_gestures = 2130968722;
			
			// aapt resource value: 0x7f040093
			public const int zoom_in = 2130968723;
			
			// aapt resource value: 0x7f040094
			public const int zoom_out = 2130968724;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Mono_Android_Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
